# Generated by Django 5.2.4 on 2025-12-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='apellido_materno',
            new_name='apellido_materno_alumno',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='apellido_paterno',
            new_name='apellido_paterno_alumno',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='nombre',
            new_name='nombre_alumno',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='apellido_materno',
            new_name='apellido_materno_tutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='apellido_paterno',
            new_name='apellido_paterno_tutor',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='nombre',
            new_name='nombre_tutor',
        ),
    ]
