# Generated by Django 5.2.4 on 2025-12-05 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_apellido_materno_alumno_apellido_materno_alumno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='apellido_paterno_alumno',
            new_name='apellidos_alumno',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='apellido_paterno_tutor',
            new_name='apellidos_ptutor',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='apellido_materno_alumno',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='apellido_materno_tutor',
        ),
    ]
