# Generated by Django 5.2.4 on 2025-12-05 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_apellido_paterno_alumno_alumno_apellidos_alumno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.grupo'),
        ),
    ]
