# Generated by Django 5.2.4 on 2025-12-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alumno_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegiatura',
            name='referencia',
            field=models.CharField(max_length=50),
        ),
    ]
