# Generated by Django 5.2.4 on 2025-12-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_colegiatura_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegiatura',
            name='mes',
            field=models.CharField(default='Enero', max_length=20),
        ),
    ]
