# Generated by Django 5.2.4 on 2025-12-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_colegiatura_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegiatura',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=10),
        ),
    ]
