# Generated by Django 5.2.4 on 2025-12-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_colegiatura_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegiatura',
            name='mes',
            field=models.CharField(max_length=20),
        ),
    ]
