# Generated by Django 5.2.4 on 2025-12-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_colegiatura_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegiatura',
            name='metodo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('TARJETA', 'Tarjeta de Crédito/Débito')], default='EFECTIVO', max_length=20),
        ),
    ]
